apiVersion: v1
kind: ServiceAccount
metadata:
  name: dya-controller
  namespace: dya-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dya-controller
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["dya.kryntelxf.com"]
  resources: ["assets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["dya.kryntelxf.com"]
  resources: ["assets/status"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dya-controller
subjects:
- kind: ServiceAccount
  name: dya-controller
  namespace: dya-system
roleRef:
  kind: ClusterRole
  name: dya-controller
  apiGroup: rbac.authorization.k8s.io
